Linter review
mpicollo-wolox/typescript-base pull request #6
Opened 2019-09-09 16:54 UTC by anaturrillo

## Summary

I added several typescript specific rules to an existing es-lint file. The idea is to work with them (some might be unnecessary strict) to definitely decide which ones should we keep. Using the linter I modified the project to comply with the new rules.

2019-09-10 20:03 UTC, mpicollo-wolox commented on .eslintrc.js
> +    "quotes": "off",
This rule is already defined in wolox config [here](https://github.com/Wolox/eslint-config-wolox/blob/master/index.js#L213), check repeated rules and avoid redefine that rules (unless is necessary for typescript)

2019-09-12 13:29 UTC, picollomartin requested changes
Amazing work here 🎉

2019-09-12 13:29 UTC, picollomartin commented on .eslintrc.js
> +    "require-await": "off",
This rules conflicts with [Wolox standard ](https://github.com/Wolox/eslint-config-wolox/blob/master/index.js#L142)

2019-09-12 13:29 UTC, picollomartin commented on .eslintrc.js
> +    "no-useless-constructor": "off",
This should be "error" ?

2019-09-12 13:29 UTC, picollomartin commented on types/config/index.d.ts
> +      // eslint-disable-next-line @typescript-eslint/camelcase
It seems a bad idea have this rule, because we use snake_case as standard for input/output of APIs

2019-09-12 13:29 UTC, picollomartin commented on package.json
> +    "pg-hstore": "^2.3.3",
You need this module ?

2019-09-12 13:29 UTC, picollomartin commented on package.json
> +    "tslint": "^5.19.0",
This should be a devDependency

2019-09-12 13:29 UTC, picollomartin commented on types/models/index.d.ts
> +export interface IModels {
Prepend `I` before name of interface seems tricky to me, for example types does not reflect that (we not use `T` before type name).

2019-09-12 13:29 UTC, picollomartin commented on config/db.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
If is a javascript file, typescript rules still applies ?

2019-09-12 13:29 UTC, picollomartin commented on package.json
>      "lint-fix": "eslint \"**/*.js\" --fix --ignore-pattern ./.eslintrc.js",
Change `lint-fix` and `lint-diff` too

2019-09-12 16:44 UTC, anaturrillo commented on package.json
> +    "pg-hstore": "^2.3.3",
I actually don't remember why I added it

2019-09-12 16:58 UTC, anaturrillo commented on config/db.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
Yes, IDE checks it (and I can't stand seeing the red flag in the file) but we are not running the linter on js files. Should we?
@typescript-eslint/parser supports both js and ts.

2019-09-13 20:06 UTC, picollomartin approved these changes
Nice 🏄

2019-09-16 22:36 UTC, merged